//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOPProjectBattleship2
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameShipConfigurations
    {
        public int ID { get; set; }
        public string PlayerFK { get; set; }
        public Nullable<int> GameFK { get; set; }
        public string Coordinate { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Players Players { get; set; }
    }
}
